apiVersion: apps/v1
kind: Deployment
metadata:
  name: javademo
  labels:
    app: javademo
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1729956696108
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
        - name: javademo
          image: gckacr.azurecr.io/image-workflow-1729956696108:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
